version: '3.8'
services:
  db:
    image: postgres:15-alpine
    container_name: postgres-db-compose
    environment:
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=
    ports:
      - "5433:5432"
    expose:
      - "5433"
    volumes:
      - db:/data/postgres

  app:
    build:
      context: ./
    image: attraction_app
    container_name: app-container-compose
    environment:
      - DB_HOST=db
      - DB_PORT=
      - DB_NAME=
      - DB_USER=
      - DB_PASSWORD=
    ports:
      - "8080:8080"
    depends_on:
      - db
    links:
      - db

volumes:
  db:
